ListCBV/ListCBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^app/', include('app.urls'))
]

ListCBV/app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(), name = 'list'),
    url(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(), name = 'detail')
]

ListCBV/app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE,related_name='students')

    def __str__(self):
        return self.name

ListCBV/app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from app import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'app/school_detail.html'

ListCBV/app/templates/app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CBV - LIST and Detail View</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="navbar-brand"><a href="{% url 'app:list' %}">Schools</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

ListCBV/app/templates/app/school_detail.html
{% extends "app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details:</h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>

  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old. </p>
  {% endfor %}
</div>
{% endblock %}

ListCBV/app/templates/app/school_list.html
{% extends "app/basic_app_base.html" %}

{% block body_block %}
<h1>Welcome to a list of all the schools!</h1>
<ol>
  {% for school in schools %}
  <!-- <h2><li>{{ school.name }}</li></h2> -->
  <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
  {% endfor %}
</ol>
{% endblock %}

ListCBV/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CBV - LIST and Detail View</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="navbar-brand"><a href="{% url 'app:list' %}">Schools</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

ListCBV/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Hello Page</h1>
  </div>
{% endblock %}